"""empty message

Revision ID: 0616c307f9f5
Revises: 4763161377e5
Create Date: 2018-12-14 15:39:44.790157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0616c307f9f5'
down_revision = '4763161377e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('km_interval', sa.Integer(), nullable=True),
    sa.Column('km_interval_start', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.Column('time_interval', sa.Interval(), nullable=True),
    sa.Column('time_interval_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('tasks')
    # ### end Alembic commands ###
