"""empty message

Revision ID: 2dbb1eeb4e0c
Revises: 9d6444049ee0
Create Date: 2019-01-15 16:08:30.349751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2dbb1eeb4e0c'
down_revision = '9d6444049ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('community_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=120), nullable=False),
                    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
