"""empty message

Revision ID: 6ed4317c5750
Revises: 2dbb1eeb4e0c
Create Date: 2019-02-01 14:57:24.708713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6ed4317c5750'
down_revision = '2dbb1eeb4e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
