"""empty message

Revision ID: 806237374814
Revises: 10f23468d17a
Create Date: 2018-11-07 18:04:23.265844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import table

revision = '806237374814'
down_revision = '10f23468d17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))

    # Data migration
    users = table(
        'users',
        sa.Column('email', sa.String(length=120), nullable=False),
    )
    op.execute(
        users.update().values({'email': 'data-migration@carbulator.net'})
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
