"""empty message

Revision ID: 84e4b31bc2db
Revises: 0616c307f9f5
Create Date: 2018-12-15 12:41:34.119257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84e4b31bc2db'
down_revision = '0616c307f9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instances',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.Column('km_created_at', sa.DECIMAL(precision=10, scale=1), nullable=True),
                    sa.Column('is_open', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('tasks', sa.Column('km_next_instance', sa.DECIMAL(precision=10, scale=1), nullable=True))
    op.add_column('tasks', sa.Column('time_next_instance', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tasks', 'time_interval_start')
    op.drop_column('tasks', 'km_interval_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('km_interval_start', mysql.DECIMAL(precision=10, scale=1), nullable=True))
    op.add_column('tasks', sa.Column('time_interval_start', mysql.DATETIME(), nullable=True))
    op.drop_column('tasks', 'time_next_instance')
    op.drop_column('tasks', 'km_next_instance')
    op.drop_table('task_instances')
    # ### end Alembic commands ###
