"""empty message

Revision ID: 9d6444049ee0
Revises: afc8f3c63277
Create Date: 2018-12-30 18:59:09.548377

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d6444049ee0'
down_revision = 'afc8f3c63277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_instances', sa.Column('finished_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_instances', 'users', ['finished_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_instances', type_='foreignkey')
    op.drop_column('task_instances', 'finished_by_id')
    # ### end Alembic commands ###
