"""empty message

Revision ID: 9e71e759b9d8
Revises: f0f8fe380410
Create Date: 2019-02-06 18:47:21.733981

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import table

revision = '9e71e759b9d8'
down_revision = 'f0f8fe380410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_reocurrent', sa.Boolean(), nullable=False))

    # Data migration
    tasks = table(
        'tasks',
        sa.Column('is_reocurrent', sa.Boolean(), nullable=False),
    )
    op.execute(
        tasks.update().values({'is_reocurrent': True})
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_reocurrent')
    # ### end Alembic commands ###
