"""empty message

Revision ID: f630edffbf2b
Revises: 806237374814
Create Date: 2018-11-26 17:38:36.473653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f630edffbf2b'
down_revision = '806237374814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_hash', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_hash')
    # ### end Alembic commands ###
